import javax.swing.*;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.NoSuchElementException;
import java.util.Scanner;

public class NewJFrame extends javax.swing.JFrame {
    int correctOption;
    int numberOfQuestions;
    File file = new File("QuestionBank.txt");
    Scanner sc = new Scanner(file);
    Test test = new Test();

    /**
     * Creates new form NewJFrame
     */

    public NewJFrame() throws FileNotFoundException {
        initComponents();
        setQuestion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("jRadioButton1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("jRadioButton3");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("jRadioButton4");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Next ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton3)
                                                .addGap(58, 58, 58)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jRadioButton4)
                                                        .addComponent(jRadioButton2)))
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton1)
                                        .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButton4)
                                        .addComponent(jRadioButton3))
                                .addGap(37, 37, 37)
                                .addComponent(jButton2)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        /*switch (correctOption) {
            case 1:
                if (jRadioButton1.isSelected())
                    JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                else
                    JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                break;
            case 2:
                if (jRadioButton2.isSelected())
                    JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                else
                    JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                break;
            case 3:
                if (jRadioButton3.isSelected())
                    JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                else
                    JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                break;
            case 4:
                if (jRadioButton4.isSelected())
                    JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                else
                    JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                break;
            default:
                JOptionPane.showMessageDialog(new JFrame(), "Select an Option");
        }*/


    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        if (jRadioButton1.isSelected()) {
            if (correctOption == 1) {
                //JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                test.correctAnswers.add(1);
            } else {
                //JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                test.correctAnswers.add(0);
            }

        } else if (jRadioButton2.isSelected()) {
            if (correctOption == 2) {
                //JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                test.correctAnswers.add(1);
            } else {
                //JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                test.correctAnswers.add(0);
            }
        } else if (jRadioButton3.isSelected()) {
            if (correctOption == 3) {
                //JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                test.correctAnswers.add(1);
            } else {
                //JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                test.correctAnswers.add(0);
            }
        } else if (jRadioButton4.isSelected()) {
            if (correctOption == 4) {
                //JOptionPane.showMessageDialog(new JFrame(), "Correct Answer");
                test.correctAnswers.add(1);
            } else {
                //JOptionPane.showMessageDialog(new JFrame(), "Wrong Answer");
                test.correctAnswers.add(0);
            }
        }
        setQuestion();
        buttonGroup1.clearSelection();
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
            }
        });
    }

    private void setQuestion() {
        try {
            String s = sc.nextLine();
            String[] x = s.split("/");
            jTextArea1.setText(x[1]);
            jRadioButton1.setText(x[2]);
            jRadioButton2.setText(x[3]);
            jRadioButton3.setText(x[4]);
            jRadioButton4.setText(x[5]);
            correctOption = Integer.parseInt(x[6]);
        } catch (NoSuchElementException e) {
            test.calculateScore();
            JOptionPane.showMessageDialog(new JFrame(), "Your Score is " + test.getScore());
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }


    }

    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration
}
